# Application name
spring.application.name=eureka-server

# Eureka server port
server.port=8761

# Eureka server does not self-register
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Enable Eureka web dashboard
eureka.dashboard.enabled=true
