server.port=8080
spring.application.name=api-gateway

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Route vers project-service
spring.cloud.gateway.routes[0].id=project-service
spring.cloud.gateway.routes[0].uri=lb://project-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**

# Condidatures
spring.cloud.gateway.routes[1].id=microservice-condidature-condidatures
spring.cloud.gateway.routes[1].uri=lb://microservice-condidature
spring.cloud.gateway.routes[1].predicates[0]=Path=/condidature-api/condidatures/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/condidature-api/(?<segment>.*), /api/${segment}

# Contrats
spring.cloud.gateway.routes[2].id=microservice-condidature-contrats
spring.cloud.gateway.routes[2].uri=lb://microservice-condidature
spring.cloud.gateway.routes[2].predicates[0]=Path=/condidature-api/contrats/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/condidature-api/(?<segment>.*), /api/${segment}


# Freelancer Service
spring.cloud.gateway.routes[3].id=freelancer-service
spring.cloud.gateway.routes[3].uri=lb://freelancer-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/freelancer-api/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/freelancer-api/(?<segment>.*), /api/${segment}
# Formation Service
spring.cloud.gateway.routes[4].id=formation-service
spring.cloud.gateway.routes[4].uri=lb://formation-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/formation-api/**
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/formation-api/(?<segment>.*), /api/${segment}

# User Service
#spring.cloud.gateway.routes[5].id=micro-user-service
#spring.cloud.gateway.routes[5].uri=lb://micro-user
#spring.cloud.gateway.routes[5].predicates[0]=Path=/auth/**
#spring.cloud.gateway.routes[5].filters[0]=RewritePath=/auth/(?<segment>.*), /auth/${segment}


spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true